services:

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    networks:
      - dev

  frontend:
    build:
      context: ./react-app/frontend
    ports:
      - "3001:3000"
    networks:
      - dev 

networks:
  dev:
